var http = require('http');

r = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sit amet risus nunc. Pellentesque arcu nibh, blandit eu elementum sit amet, aliquam vel sem. Nam id libero maximus enim accumsan egestas. Donec et erat quis nulla molestie porta eu in tellus. Duis tempus enim aliquam, imperdiet arcu eu, porta urna. Aliquam porttitor at augue eu malesuada. Quisque id porttitor augue. Ut a congue purus. Fusce vestibulum risus vel blandit facilisis. Praesent euismod, lacus sed commodo euismod, diam mi eleifend odio, in tempus sem massa vitae libero.

Quisque ut nisl nulla. Nulla iaculis mauris quis metus dictum placerat. Cras pulvinar felis vel est maximus aliquam. Curabitur non feugiat nisl, nec auctor libero. Quisque commodo, orci eu sollicitudin tincidunt, dui purus dictum odio, sit amet dignissim sapien leo quis eros. Fusce dui sapien, laoreet eu sem eget, tempor tristique sem. Quisque dignissim est mi, eu volutpat nibh malesuada vel. Maecenas mollis, tellus vel blandit viverra, orci libero commodo ex, eu egestas odio nisl id lorem. Donec eros nibh, finibus non velit maximus, gravida molestie nunc. Proin eget porttitor sem. Sed rhoncus felis sit amet pellentesque accumsan. Donec quis efficitur sapien. Aliquam et nibh at felis porttitor sodales et id nisl. Vivamus cursus eros eu orci suscipit pretium et nec nibh.

Pellentesque felis lorem, porta non libero et, tincidunt laoreet massa. Donec ut sodales ligula. Quisque tellus ex, dignissim non interdum eu, blandit et felis. Donec pulvinar arcu nunc, at malesuada mi viverra quis. Maecenas in nisi euismod, venenatis urna a, ornare nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus egestas nec ex eget sollicitudin. Sed pharetra vitae nunc quis mollis. Nunc tincidunt erat interdum, bibendum magna ut, sollicitudin libero.

Quisque tincidunt nulla velit, id suscipit arcu placerat non. Vestibulum sit amet purus enim. Quisque porttitor turpis vel leo tristique placerat nec vel enim. Quisque accumsan molestie erat, non blandit sapien venenatis vel. Etiam vel dictum urna. Aenean euismod, neque at tincidunt imperdiet, lectus eros rhoncus neque, vel dapibus enim lorem nec elit. Fusce elementum molestie nisl, a faucibus felis maximus consequat. Donec fermentum sem eget elit rutrum mattis. Donec tincidunt sem ac mauris luctus vehicula. Ut id gravida nisl, non molestie dui. Cras ornare accumsan lacus, non pharetra tellus placerat ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin finibus elit eu nunc blandit eleifend.

Cras gravida, massa ultricies rhoncus ultricies, ante justo consequat augue, at pellentesque mauris ligula eu magna. Praesent nisl enim, interdum in sollicitudin dignissim, sollicitudin et mi. Suspendisse eu leo ut nunc placerat convallis. Sed volutpat, sem id pulvinar placerat, tellus ante interdum felis, luctus consectetur odio libero vel leo. Donec ut quam porttitor, tristique nunc sit amet, ultricies ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam viverra mattis nibh ac dapibus. Sed sit amet ultricies velit, in suscipit purus. Curabitur vitae nulla eros. Quisque ipsum leo, tempor non lobortis sit amet, aliquet et velit. Donec posuere tortor tortor, eget aliquam purus aliquet et. Phasellus vel dui lobortis, consectetur metus volutpat, lacinia tortor. Suspendisse potenti.

Sed ullamcorper, orci et laoreet congue, sem eros ornare metus, id tempus orci justo ut mi. Etiam non pellentesque sapien. Phasellus ornare arcu eu ex ultricies porta. Curabitur turpis quam, hendrerit ut consequat at, facilisis et tortor. Aliquam vitae condimentum lectus. Donec rutrum blandit turpis, sit amet commodo mi laoreet nec. Nam scelerisque turpis neque, eget lobortis arcu tincidunt sed. Maecenas molestie libero vitae mi varius ullamcorper. In tincidunt ante mi, in convallis justo eleifend ac. Sed tempus sit amet massa at pharetra. Donec quis tempus nulla. Fusce id orci vestibulum, rhoncus sapien vitae, tempus leo. Quisque elit lectus, vehicula duis.`

for(let i = 2; i < process.argv.length; i++){
    let port = parseInt(process.argv[i])
    //create a server object:
    http.createServer(function (req, res) {
        res.write(r); //write a response to the client
        res.end(); //end the response
    }).listen(port); //the server object listens on port 8080
}
